name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Environment Variables
        run: |
          cat .env.production >> $GITHUB_ENV

      - name: Build Application
        run: |
          npm ci
          npm run build:production

      - name: Deploy Application
        run: aws s3 sync build/ s3://domain.tld --delete
